[package]
name = "class"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.48", features = ["derive"]}
colored = "3.0.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tabled = { version = "0.20.0", features = ["ansi"] }
